### ISSUE TITLE
end game tests

### ISSUE THREAD

**Issue by beckermr** [des-science/eastlake#51]
- [ ] get setup scripts together for erin (matt)
- [ ] test variable weight map (matt)
- [ ] write cosmic+bad column generator for montara and test (sid?)
- [ ] get things running on condor (erin)

**Comment by esheldon** [comment]
Should we commit an environment file for conda as well?

**Comment by beckermr** [comment]
You'll also need the various yaml configs here: https://www.cosmo.bnl.gov/Private/gpfs/workarea/beckermr/des-y6-analysis/2023_05_09_imsims_noise_debug/

**Comment by esheldon** [comment]
I see this warning, is it ok?
```
Warning: config dict contains the following unexpected fields: ['pipeline', 'galsim_montara', 'true_detection', 'pizza_cutter', 'metadetect', 'star'].
```

**Comment by esheldon** [comment]
I edited the eastlake config where it had number of jobs `n_jobs` set for both pizza cutter and metadetect.   I changed them to 1 but it is using all the cores.

**Comment by esheldon** [comment]
I think I see the problem:  the part run *before* pizza cutter is using all cores.  How do I set that to 1 core?

**Comment by esheldon** [comment]
That worked, thanks.

The field is "nproc"

**Comment by esheldon** [comment]
I ran with `badpixfromfits` in the config
```yaml
  # uses the bit mask from the real image                                                                                                                                                                                                                      
  badpixfromfits:                                                                                                                                                                                                                                              
    hdu: 1                                                                                                                                                                                                                                                     
    mask_hdu: 2                                                                                                                                                                                                                                                
    mask_file: "$orig_image_path"
```

and am now getting this

```
Start file 0 = /gpfs/mnt/gpfs02/astro/desdata/esheldon/lensing/des-lensing/y6-sims/mysims/mysim_outputs_plus_18_1234/des-pizza-slices-y6-v15-nostars/DES0433-2332/sources-r/OPS_Taiga/finalcut/Y5A1/r3518/20180107/D00710310/p01/red/immask/D00710310_r_c34_r35
18p01_immasked.fits
Start file 1 = /gpfs/mnt/gpfs02/astro/desdata/esheldon/lensing/des-lensing/y6-sims/mysims/mysim_outputs_plus_18_1234/des-pizza-slices-y6-v15-nostars/DES0433-2332/sources-r/OPS_Taiga/finalcut/Y5A1/r3567/20141216/D00388613/p02/red/immask/D00388613_r_c55_r35
67p02_immasked.fits
adding bkg with mean 0.00e+00 from file /gpfs/mnt/gpfs02/astro/desdata/esheldon/lensing/des-lensing/y6-sims/mysims/mysim_outputs_plus_18_1234/des-pizza-slices-y6-v15-nostars/DES0433-2332/sources-r/OPS_Taiga/finalcut/Y5A1/r3518/20180107/D00710310/p01/red/b
kg/D00710310_r_c34_r3518p01_bkg.fits.fz
Process-1: Exception caught for file 0 = /gpfs/mnt/gpfs02/astro/desdata/esheldon/lensing/des-lensing/y6-sims/mysims/mysim_outputs_plus_18_1234/des-pizza-slices-y6-v15-nostars/DES0433-2332/sources-r/OPS_Taiga/finalcut/Y5A1/r3518/20180107/D00710310/p01/red/
immask/D00710310_r_c34_r3518p01_immasked.fits
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/astro/desdata/esheldon/mambaforge/envs/y6sims/lib/python3.10/site-packages/galsim/config/util.py", line 734, in worker
    result = job_func(**kwargs)
  File "/gpfs/mnt/gpfs02/astro/desdata/esheldon/mambaforge/envs/y6sims/lib/python3.10/site-packages/galsim/config/output.py", line 260, in BuildFile
    data = builder.addExtraOutputHDUs(config, data, logger)
  File "/gpfs/mnt/gpfs02/astro/desdata/esheldon/mambaforge/envs/y6sims/lib/python3.10/site-packages/galsim/config/output.py", line 546, in addExtraOutputHDUs
    data = AddExtraOutputHDUs(config, data, logger)
  File "/gpfs/mnt/gpfs02/astro/desdata/esheldon/mambaforge/envs/y6sims/lib/python3.10/site-packages/galsim/config/extra.py", line 284, in AddExtraOutputHDUs
    raise GalSimConfigValueError("hdu is invalid or a duplicate.",hdu)
galsim.errors.GalSimConfigValueError: hdu is invalid or a duplicate. Value 1
```

**Comment by beckermr** [comment]
Did you comment out the other pixel map section?

**Comment by esheldon** [comment]
sorry which part do you mean?

**Comment by esheldon** [comment]
thanks, that seems to work
